default: &default
  host: <%= ENV.fetch("POSTGRESQL_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRESQL_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD") { '' } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POSTGRESQL_POOL") { 5 } %>

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test